// Generated by gencpp from file testeturtle/goResponse.msg
// DO NOT EDIT!


#ifndef TESTETURTLE_MESSAGE_GORESPONSE_H
#define TESTETURTLE_MESSAGE_GORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace testeturtle
{
template <class ContainerAllocator>
struct goResponse_
{
  typedef goResponse_<ContainerAllocator> Type;

  goResponse_()
    : var(0)  {
    }
  goResponse_(const ContainerAllocator& _alloc)
    : var(0)  {
  (void)_alloc;
    }



   typedef int64_t _var_type;
  _var_type var;




  typedef boost::shared_ptr< ::testeturtle::goResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::testeturtle::goResponse_<ContainerAllocator> const> ConstPtr;

}; // struct goResponse_

typedef ::testeturtle::goResponse_<std::allocator<void> > goResponse;

typedef boost::shared_ptr< ::testeturtle::goResponse > goResponsePtr;
typedef boost::shared_ptr< ::testeturtle::goResponse const> goResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::testeturtle::goResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::testeturtle::goResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace testeturtle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::testeturtle::goResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::testeturtle::goResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testeturtle::goResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testeturtle::goResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testeturtle::goResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testeturtle::goResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::testeturtle::goResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9559ec07ba73a7e45bf3354138657b84";
  }

  static const char* value(const ::testeturtle::goResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9559ec07ba73a7e4ULL;
  static const uint64_t static_value2 = 0x5bf3354138657b84ULL;
};

template<class ContainerAllocator>
struct DataType< ::testeturtle::goResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "testeturtle/goResponse";
  }

  static const char* value(const ::testeturtle::goResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::testeturtle::goResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 var\n\
\n\
";
  }

  static const char* value(const ::testeturtle::goResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::testeturtle::goResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.var);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::testeturtle::goResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::testeturtle::goResponse_<ContainerAllocator>& v)
  {
    s << indent << "var: ";
    Printer<int64_t>::stream(s, indent + "  ", v.var);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESTETURTLE_MESSAGE_GORESPONSE_H
