// Generated by gencpp from file testeturtle/talkResponse.msg
// DO NOT EDIT!


#ifndef TESTETURTLE_MESSAGE_TALKRESPONSE_H
#define TESTETURTLE_MESSAGE_TALKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace testeturtle
{
template <class ContainerAllocator>
struct talkResponse_
{
  typedef talkResponse_<ContainerAllocator> Type;

  talkResponse_()
    : val(0)  {
    }
  talkResponse_(const ContainerAllocator& _alloc)
    : val(0)  {
  (void)_alloc;
    }



   typedef int64_t _val_type;
  _val_type val;




  typedef boost::shared_ptr< ::testeturtle::talkResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::testeturtle::talkResponse_<ContainerAllocator> const> ConstPtr;

}; // struct talkResponse_

typedef ::testeturtle::talkResponse_<std::allocator<void> > talkResponse;

typedef boost::shared_ptr< ::testeturtle::talkResponse > talkResponsePtr;
typedef boost::shared_ptr< ::testeturtle::talkResponse const> talkResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::testeturtle::talkResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::testeturtle::talkResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace testeturtle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::testeturtle::talkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::testeturtle::talkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testeturtle::talkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testeturtle::talkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testeturtle::talkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testeturtle::talkResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::testeturtle::talkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58ba147ce3095b36344060f1e5dd0b05";
  }

  static const char* value(const ::testeturtle::talkResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58ba147ce3095b36ULL;
  static const uint64_t static_value2 = 0x344060f1e5dd0b05ULL;
};

template<class ContainerAllocator>
struct DataType< ::testeturtle::talkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "testeturtle/talkResponse";
  }

  static const char* value(const ::testeturtle::talkResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::testeturtle::talkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 val\n\
\n\
";
  }

  static const char* value(const ::testeturtle::talkResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::testeturtle::talkResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct talkResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::testeturtle::talkResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::testeturtle::talkResponse_<ContainerAllocator>& v)
  {
    s << indent << "val: ";
    Printer<int64_t>::stream(s, indent + "  ", v.val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESTETURTLE_MESSAGE_TALKRESPONSE_H
